COMMAND: ./prog1 2>&1 > tmpfile | ./prog2; ./prog3 < tmpfile
COMMAND_ID: 4
GRADING_LOG_PATH: /tmp/testlab_autograde
PROG_A: fancyLs
PROG_B: ticTacToe
TKN_PROG_A: 284ee28e02b85b6e
TKN_PROG_B: af3e8769a9e6fc37
