ALICE_PROCNAME: latosha
BOB_PROCNAME: lamar
GRADING_LOG_PATH: /tmp/processlab_autograde
OBFUSCATE_MASK: 273bd05ca0ca4b982b102e4a3364e86b8b0e1344164f3586ef2c0a33a115b16a7dd7e8ad308b4a3181161440e9ca1e94be37e739476ee3319ae607933fc92da493679037d9bf688a16395c14def6dc9c262a560c8e14175d7d5497ac3dc7c75a332136c9d1b8f288a3f53b71a665d66e2b95b940cfeac7e71224b37fe000973892f4546bdd9f60ceb5c4d096c26e8811a9d92efbe2d6c4db0782996767c3b878ef84c96450af0fdb26a0240d743f711ef56ddd0ebbb9e887c8ca0589c01a5786dcec4693dc943a80616737fc0897d3a3d27f723d03c60a6efe09ee39efd5ad8589029a38cf1d5917be93358b0165bc6130e0fa63627eb09c636ec96d2e05035b6063eea4e1b91c2ca14b21847a49cd049e54a816342b651ee2ddc1fa22f2194ef28b0af35001d060274e5655
PART2_LTRACE_LOG_PATH: /tmp/processlab_autograde_ltrace_part2
PART2_PRINTF_PROCESSES_LIST: level0, level1.1, level1.4, level2.1, level2.3, level2.4
PART2_PROCESS_TREE:
  children:
  - children:
    - level: 2
      name: level2.1
      print: true
      token: ''
    - level: 2
      name: level2.2
      print: false
      token: ''
    level: 1
    name: level1.1
    print: true
    token: 19479a
  - children:
    - level: 2
      name: level2.3
      print: true
      token: ''
    level: 1
    name: level1.2
    print: false
    token: 736cb2
  - children:
    - level: 2
      name: level2.4
      print: true
      token: ''
    level: 1
    name: level1.3
    print: false
    token: 952ecc
  - children:
    - level: 2
      name: level2.5
      print: false
      token: ''
    level: 1
    name: level1.4
    print: true
    token: 3e7dc9
  level: 0
  name: level0
  print: true
  token: 19479a736cb2952ecc3e7dc9
PART2_PROCESS_TREE_PSTRICKS: \\\pstree{\\\Tcircle{level0}}{\\\pstree{\\\Tcircle{level1.1}}{\\\Tcircle{level2.1}
  \\\Tcircle{level2.2} }\\\pstree{\\\Tcircle{level1.2}}{\\\Tcircle{level2.3} }\\\pstree{\\\Tcircle{level1.3}}{\\\Tcircle{level2.4}
  }\\\pstree{\\\Tcircle{level1.4}}{\\\Tcircle{level2.5} }}
PART2_Q4_ENV_KEY: TOKEN_DISABLE_FORK
PART2_Q4_ENV_KEY_LENGTH: 18
PART2_Q4_ENV_KEY_OBF: '{102, 120, 120, 39, 42, 111, 113, 42, 50, 113, 33, 45, 113,
  61, 127, 119, 96, 41}'
PART2_Q4_PROC_NUM: 2
PART2_STRACE_LOG_PATH: /tmp/processlab_autograde_strace_part2
PID_KEY: -pid
PROC0_LEVEL: 0
PROC0_NAME: level0
PROC0_TOKEN: 19479a736cb2952ecc3e7dc9
PROC0_TOKEN_LENGTH: 24
PROC0_TOKEN_OBF: '{3, 14, 7, 85, 93, 81, 2, 80, 87, 83, 1, 83, 13, 87, 11, 93, 81,
  1, 2, 85, 5, 1, 87, 88}'
PROC1_LEVEL: 1
PROC1_NAME: level1.4
PROC1_TOKEN: 3e7dc9
PROC1_TOKEN_LENGTH: 6
PROC1_TOKEN_OBF: '{1, 82, 4, 6, 7, 9}'
PROC2_LEVEL: 2
PROC2_NAME: level2.5
PROC2_TOKEN: ''
PROC2_TOKEN_LENGTH: 0
PROC2_TOKEN_OBF: '{}'
PROC3_LEVEL: 1
PROC3_NAME: level1.3
PROC3_TOKEN: 952ecc
PROC3_TOKEN_LENGTH: 6
PROC3_TOKEN_OBF: '{11, 2, 1, 7, 7, 83}'
PROC4_LEVEL: 2
PROC4_NAME: level2.4
PROC4_TOKEN: ''
PROC4_TOKEN_LENGTH: 0
PROC4_TOKEN_OBF: '{}'
PROC5_LEVEL: 1
PROC5_NAME: level1.2
PROC5_TOKEN: 736cb2
PROC5_TOKEN_LENGTH: 6
PROC5_TOKEN_OBF: '{5, 4, 5, 1, 6, 2}'
PROC6_LEVEL: 2
PROC6_NAME: level2.3
PROC6_TOKEN: ''
PROC6_TOKEN_LENGTH: 0
PROC6_TOKEN_OBF: '{}'
PROC7_LEVEL: 1
PROC7_NAME: level1.1
PROC7_TOKEN: 19479a
PROC7_TOKEN_LENGTH: 6
PROC7_TOKEN_OBF: '{3, 14, 7, 85, 93, 81}'
PROC8_LEVEL: 2
PROC8_NAME: level2.2
PROC8_TOKEN: ''
PROC8_TOKEN_LENGTH: 0
PROC8_TOKEN_OBF: '{}'
PROC9_LEVEL: 2
PROC9_NAME: level2.1
PROC9_TOKEN: ''
PROC9_TOKEN_LENGTH: 0
PROC9_TOKEN_OBF: '{}'
Q1_LTRACE_LOG_PATH: /tmp/processlab_autograde_ltrace_q1
TOKEN1: 826559d57d9b762c63fade93
TOKEN1_LENGTH: 24
TOKEN1_OBF: '{10, 5, 5, 87, 81, 9, 81, 86, 86, 84, 90, 3, 3, 84, 11, 91, 4, 81, 87,
  81, 86, 0, 13, 82}'
TOKEN_1: 17bf1cd0638fa112c55ddbc1a3e85aa6
TOKEN_1_LEN: 16
TOKEN_1_OBF: '{82, 83, 0, 4, 84, 6, 86, 82, 87, 87, 91, 2, 87, 80, 3, 80, 5, 3, 7,
  86, 83, 85, 0, 1, 82, 86, 92, 11, 12, 86, 7, 2}'
